# Generated by Django 5.2.5 on 2025-08-06 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empaques', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentation',
            name='size',
            field=models.CharField(choices=[('Jumbo', 'Jumbo'), ('XLarge', 'X-Large'), ('Large', 'Large'), ('Standard', 'Standard'), ('Small', 'Small'), ('Tips', 'Tips')], default='Standard', help_text='Elige el tamaño de la presentación', max_length=20),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
