# Generated by Django 5.2.5 on 2025-08-07 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empaques', '0002_presentation_size_alter_presentation_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presentation',
            name='size',
        ),
        migrations.AddField(
            model_name='shipmentitem',
            name='size',
            field=models.CharField(choices=[('Jumbo', 'Jumbo'), ('XLarge', 'X-Large'), ('Large', 'Large'), ('Standard', 'Standard'), ('Small', 'Small'), ('Tips', 'Tips')], default='Standard', help_text='Tamaño de esta línea del embarque', max_length=20),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
