# Generated by Django 5.2.5 on 2025-08-07 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empaques', '0003_remove_presentation_size_shipmentitem_size_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='shipmentitem',
            unique_together=set(),
        ),
    ]
