# Generated by Django 5.2.5 on 2025-08-07 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empaques', '0004_alter_shipmentitem_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='box',
            field=models.CharField(blank=True, max_length=30, verbose_name='Caja'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='box_conditions',
            field=models.CharField(blank=True, max_length=100, verbose_name='Condiciones de la caja'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='box_free_of_odors',
            field=models.CharField(blank=True, max_length=50, verbose_name='Caja libre de olores'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='box_plates',
            field=models.CharField(blank=True, max_length=20, verbose_name='Placas caja'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='carrier',
            field=models.CharField(blank=True, max_length=50, verbose_name='Transportista'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='chismografo',
            field=models.CharField(blank=True, max_length=50, verbose_name='Chismógrafo'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='delivery_signature',
            field=models.CharField(blank=True, max_length=50, verbose_name='Firma de entrega'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='departure_time',
            field=models.CharField(blank=True, max_length=20, verbose_name='Horario de salida'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='driver',
            field=models.CharField(blank=True, max_length=50, verbose_name='Operador'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='driver_signature',
            field=models.CharField(blank=True, max_length=50, verbose_name='Firma de operador'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='ryan',
            field=models.CharField(blank=True, max_length=50, verbose_name='Ryan'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='seal_1',
            field=models.CharField(blank=True, max_length=30, verbose_name='Sello 1'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='seal_2',
            field=models.CharField(blank=True, max_length=30, verbose_name='Sello 2'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='seal_3',
            field=models.CharField(blank=True, max_length=30, verbose_name='Sello 3'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='seal_4',
            field=models.CharField(blank=True, max_length=30, verbose_name='Sello 4'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='tractor_plates',
            field=models.CharField(blank=True, max_length=20, verbose_name='Placas tractor'),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='conversion_factor',
            field=models.DecimalField(decimal_places=16, max_digits=32),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='date',
            field=models.DateField(verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=30, verbose_name='Número de factura'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='tracking_number',
            field=models.CharField(max_length=30, verbose_name='Número de orden'),
        ),
    ]
