# Generated by Django 5.2.5 on 2025-08-07 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empaques', '0005_shipment_box_shipment_box_conditions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipmentitem',
            name='tarima',
            field=models.PositiveIntegerField(default=1, verbose_name='Tarima'),
        ),
    ]
