# Generated by Django 5.2.5 on 2025-08-08 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empaques', '0006_shipmentitem_tarima'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipmentitem',
            name='cliente',
            field=models.CharField(choices=[('La Cima Produce', 'La Cima Produce'), ('RC Organics', 'RC Organics'), ('GH Farms', 'GH Farms'), ('Gourmet Baja Farms', 'Gourmet Baja Farms'), ('GBF Farms', 'GBF Farms')], default='La Cima Produce', max_length=32),
        ),
    ]
