# Generated by Django 5.2.5 on 2025-08-08 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empaques', '0008_alter_shipmentitem_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipmentitem',
            name='temperatura',
            field=models.CharField(blank=True, help_text='Temperatura registrada (opcional)', max_length=10, null=True),
        ),
    ]
