# Generated by Django 5.2.5 on 2025-08-08 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empaques', '0009_shipmentitem_temperatura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipmentitem',
            name='temperatura',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Temperatura registrada (puede quedar vacío)', max_digits=5, null=True),
        ),
    ]
