# Generated by Django 5.2.5 on 2025-08-12 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empaques', '0010_alter_shipmentitem_temperatura'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shipment',
            options={'permissions': [('export_reports', 'Puede exportar reportes')]},
        ),
    ]
