# Generated by Django 5.2.5 on 2025-08-21 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empaques', '0011_alter_shipment_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shipment',
            options={'permissions': [('can_download_reports', 'Puede descargar/exportar reportes')]},
        ),
    ]
