# Generated by Django 5.2.5 on 2025-08-21 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empaques', '0012_alter_shipment_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='tarimas_peco',
            field=models.PositiveIntegerField(blank=True, help_text='Número de tarimas tipo PECO en el embarque', null=True, verbose_name='Tarimas PECO'),
        ),
    ]
