# Generated by Django 5.2.5 on 2025-08-25 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empaques', '0013_shipment_tarimas_peco'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='order_empaque1',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Núm. orden Empaque N.1'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='order_gbf',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Núm. orden GBF Farms'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='order_gourmet',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Núm. orden Gourmet Baja'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='order_lacima',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Núm. orden CIMA'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='order_rc',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Núm. orden RC Organics'),
        ),
    ]
