# Generated by Django 5.2.5 on 2025-08-26 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empaques', '0014_shipment_order_empaque1_shipment_order_gbf_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipment',
            name='order_empaque1',
        ),
        migrations.AddField(
            model_name='shipment',
            name='order_gh',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Núm. orden GH Farms'),
        ),
    ]
