# Generated by Django 5.2.5 on 2025-09-18 19:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empaques', '0015_remove_shipment_order_empaque1_shipment_order_gh'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=50, unique=True, verbose_name='SKU')),
                ('name', models.CharField(max_length=120, verbose_name='Nombre')),
                ('unit', models.CharField(default='pz', max_length=20, verbose_name='Unidad')),
                ('min_stock', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Stock mínimo')),
                ('location', models.CharField(blank=True, max_length=60, verbose_name='Ubicación')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Artículo de almacén',
                'verbose_name_plural': 'Artículos de almacén',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InventoryMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('IN', 'Entrada'), ('OUT', 'Salida'), ('ADJ', 'Ajuste')], max_length=3, verbose_name='Tipo')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Fecha')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Cantidad')),
                ('reference', models.CharField(blank=True, max_length=60, verbose_name='Referencia/Documento')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='empaques.inventoryitem')),
            ],
            options={
                'verbose_name': 'Movimiento de almacén',
                'verbose_name_plural': 'Movimientos de almacén',
                'ordering': ['-date', '-id'],
            },
        ),
    ]
