# Generated by Django 5.2.5 on 2025-09-24 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empaques', '0017_alter_inventoryitem_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionDisplay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(help_text="Tamaño EXACTO tal como aparece en los ítems (p. ej. 'Jumbo', 'Small 10x10').", max_length=50)),
                ('order', models.PositiveIntegerField(default=0, help_text='Orden manual para el reporte.')),
                ('is_active', models.BooleanField(default=True)),
                ('presentation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_displays', to='empaques.presentation')),
            ],
            options={
                'verbose_name': 'Presentación en Producción',
                'verbose_name_plural': 'Presentaciones en Producción',
                'ordering': ('order', 'presentation__name', 'size'),
                'unique_together': {('presentation', 'size')},
            },
        ),
    ]
