# Generated by Django 5.2.5 on 2025-09-24 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empaques', '0018_productiondisplay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productiondisplay',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='productiondisplay',
            name='size',
            field=models.CharField(help_text="Tamaño EXACTO como se captura en los ítems (p. ej. 'Jumbo').", max_length=50),
        ),
    ]
