# Generated by Django 5.2.5 on 2025-11-05 21:53

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empaques', '0019_alter_productiondisplay_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='order_dhg',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Núm. orden AGRICOLA DH & G'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='min_stock',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='shipmentitem',
            name='cliente',
            field=models.CharField(blank=True, choices=[('La Cima Produce', 'La Cima Produce'), ('RC Organics', 'RC Organics'), ('GH Farms', 'GH Farms'), ('Gourmet Baja Farms', 'Gourmet Baja Farms'), ('GBF Farms', 'GBF Farms'), ('AGRICOLA DH & G', 'AGRICOLA DH & G')], max_length=32, null=True),
        ),
    ]
