# Generated by Django 5.2.5 on 2025-11-05 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empaques', '0020_shipment_order_dhg_alter_inventoryitem_min_stock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presentation',
            name='price',
            field=models.DecimalField(decimal_places=16, max_digits=32),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='departure_time',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Horario de salida'),
        ),
    ]
