# Generated by Django 5.2.5 on 2025-11-27 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empaques', '0021_alter_presentation_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='is_national',
            field=models.BooleanField(db_index=True, default=False, help_text="Si está activo, el embarque es 'Nacional'. Si no, es 'Exportación'."),
        ),
    ]
