# Generated by Django 5.2.5 on 2026-02-03 18:51

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arandano', '0011_alter_salidadia_destino_inventoryledger'),
        ('empaques', '0022_shipment_is_national'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleEmbarque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cajas', models.PositiveIntegerField(default=0)),
                ('kg_total', models.DecimalField(decimal_places=5, default=Decimal('0'), max_digits=14)),
                ('cs_6oz', models.PositiveIntegerField(default=0)),
                ('cs_9_8oz', models.PositiveIntegerField(default=0)),
                ('cs_18oz', models.PositiveIntegerField(default=0)),
                ('presentacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='empaques.presentation')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='empaques.shipment')),
                ('variedad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='arandano.variedad')),
            ],
        ),
    ]
