# Generated by Django 5.2.5 on 2026-02-04 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arandano', '0012_alter_salidadia_destino_and_more'),
        ('empaques', '0023_detalleembarque'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentation',
            name='cs_por_caja',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='presentation',
            name='is_arandano',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.CreateModel(
            name='VariedadPresentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presentation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empaques.presentation')),
                ('variedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arandano.variedad')),
            ],
            options={
                'unique_together': {('variedad', 'presentation')},
            },
        ),
    ]
