# Generated by Django 5.2.5 on 2026-06-02 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empaques', '0024_presentation_cs_por_caja_presentation_is_arandano_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipmentitem',
            name='cliente',
            field=models.CharField(blank=True, choices=[('La Cima Produce', 'La Cima Produce'), ('RC Organics', 'RC Organics'), ('GH Farms', 'GH Farms'), ('Gourmet Baja Farms', 'Gourmet Baja Farms'), ('GBF Farms', 'GBF Farms'), ('AGRICOLA DH & G', 'AGRICOLA DH & G'), ('AGRICOLA DH&G GONZALO', 'AGRICOLA DH&G GONZALO')], max_length=32, null=True),
        ),
    ]
