# Generated by Django 5.2.5 on 2026-06-03 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empaques', '0025_alter_shipmentitem_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='order_dhg_gonzalo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Núm. orden AGRICOLA DH&G GONZALO'),
        ),
    ]
