# Generated by Django 5.2.5 on 2026-06-11 18:46

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empaques', '0026_shipment_order_dhg_gonzalo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(choices=[('La Cima Produce', 'La Cima Produce'), ('RC Organics', 'RC Organics'), ('GH Farms', 'GH Farms'), ('Gourmet Baja Farms', 'Gourmet Baja Farms'), ('GBF Farms', 'GBF Farms'), ('AGRICOLA DH&G GONZALO', 'AGRICOLA DH&G GONZALO')], db_index=True, max_length=120)),
                ('folio', models.CharField(blank=True, max_length=50, unique=True)),
                ('fecha', models.DateField(db_index=True)),
                ('notas', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedimentos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pedimento',
                'verbose_name_plural': 'Pedimentos',
                'ordering': ('fecha', 'id'),
            },
        ),
        migrations.CreateModel(
            name='PedimentoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=12)),
                ('consumido', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedimento_items', to='empaques.inventoryitem')),
                ('pedimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='empaques.pedimento')),
            ],
        ),
        migrations.CreateModel(
            name='Remision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(choices=[('La Cima Produce', 'La Cima Produce'), ('RC Organics', 'RC Organics'), ('GH Farms', 'GH Farms'), ('Gourmet Baja Farms', 'Gourmet Baja Farms'), ('GBF Farms', 'GBF Farms'), ('AGRICOLA DH&G GONZALO', 'AGRICOLA DH&G GONZALO')], db_index=True, max_length=120)),
                ('folio', models.CharField(blank=True, max_length=50, unique=True)),
                ('fecha', models.DateField(db_index=True)),
                ('notas', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remisiones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Remisión',
                'verbose_name_plural': 'Remisiones',
                'ordering': ('-fecha', '-id'),
            },
        ),
        migrations.CreateModel(
            name='RemisionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=12)),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='remision_items', to='empaques.inventoryitem')),
                ('remision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='empaques.remision')),
            ],
        ),
    ]
