# Generated by Django 5.2.5 on 2026-06-11 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empaques', '0027_pedimento_remision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedimento',
            name='empresa',
            field=models.CharField(choices=[('La Cima Produce', 'La Cima Produce'), ('RC Organics', 'RC Organics'), ('GH Farms', 'GH Farms'), ('Gourmet Baja Farms', 'Gourmet Baja Farms'), ('GBF Farms', 'GBF Farms'), ('AGRICOLA DH & G', 'AGRICOLA DH & G'), ('AGRICOLA DH&G GONZALO', 'AGRICOLA DH&G GONZALO')], db_index=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='remision',
            name='empresa',
            field=models.CharField(choices=[('La Cima Produce', 'La Cima Produce'), ('RC Organics', 'RC Organics'), ('GH Farms', 'GH Farms'), ('Gourmet Baja Farms', 'Gourmet Baja Farms'), ('GBF Farms', 'GBF Farms'), ('AGRICOLA DH & G', 'AGRICOLA DH & G'), ('AGRICOLA DH&G GONZALO', 'AGRICOLA DH&G GONZALO')], db_index=True, max_length=120),
        ),
    ]
