# Generated by Django 5.2.5 on 2026-06-15 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empaques', '0028_alter_pedimento_empresa_alter_remision_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedimento',
            name='es_inventario_inicial',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pedimento',
            name='empresa',
            field=models.CharField(choices=[('La Cima Produce', 'La Cima Produce'), ('RC Organics', 'RC Organics'), ('GH Farms', 'GH Farms'), ('Gourmet Baja Farms', 'Gourmet Baja Farms'), ('GBF Farms', 'GBF Farms')], db_index=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='remision',
            name='empresa',
            field=models.CharField(choices=[('La Cima Produce', 'La Cima Produce'), ('RC Organics', 'RC Organics'), ('GH Farms', 'GH Farms'), ('Gourmet Baja Farms', 'Gourmet Baja Farms'), ('GBF Farms', 'GBF Farms')], db_index=True, max_length=120),
        ),
    ]
