# Generated by Django 5.2.5 on 2026-06-22 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empaques', '0029_inventario_inicial_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='order_dhg_cruces',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Núm. orden AGRICOLA DH&G CRUCES'),
        ),
        migrations.AlterField(
            model_name='shipmentitem',
            name='cliente',
            field=models.CharField(blank=True, choices=[('La Cima Produce', 'La Cima Produce'), ('RC Organics', 'RC Organics'), ('GH Farms', 'GH Farms'), ('Gourmet Baja Farms', 'Gourmet Baja Farms'), ('GBF Farms', 'GBF Farms'), ('AGRICOLA DH & G', 'AGRICOLA DH & G'), ('AGRICOLA DH&G GONZALO', 'AGRICOLA DH&G GONZALO'), ('AGRICOLA DH&G CRUCES', 'AGRICOLA DH&G CRUCES')], max_length=32, null=True),
        ),
    ]
