# Generated by Django 5.2.5 on 2026-07-13 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empaques', '0030_add_dhg_cruces'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='order_el_garal',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Núm. orden PRODUCTORA EL GARAL'),
        ),
        migrations.AlterField(
            model_name='shipmentitem',
            name='cliente',
            field=models.CharField(blank=True, choices=[('La Cima Produce', 'La Cima Produce'), ('RC Organics', 'RC Organics'), ('GH Farms', 'GH Farms'), ('Gourmet Baja Farms', 'Gourmet Baja Farms'), ('GBF Farms', 'GBF Farms'), ('AGRICOLA DH & G', 'AGRICOLA DH & G'), ('AGRICOLA DH&G GONZALO', 'AGRICOLA DH&G GONZALO'), ('AGRICOLA DH&G CRUCES', 'AGRICOLA DH&G CRUCES'), ('PRODUCTORA EL GARAL', 'PRODUCTORA EL GARAL')], max_length=32, null=True),
        ),
    ]
