# Generated by Django 5.2.5 on 2026-07-28 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empaques', '0031_add_el_garal'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='invoice_dhg',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Núm. factura AGRICOLA DH & G'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='invoice_dhg_cruces',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Núm. factura AGRICOLA DH&G CRUCES'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='invoice_dhg_gonzalo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Núm. factura AGRICOLA DH&G GONZALO'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='invoice_el_garal',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Núm. factura PRODUCTORA EL GARAL'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='invoice_gbf',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Núm. factura GBF Farms'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='invoice_gh',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Núm. factura GH Farms'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='invoice_gourmet',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Núm. factura Gourmet Baja'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='invoice_lacima',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Núm. factura CIMA'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='invoice_rc',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Núm. factura RC Organics'),
        ),
    ]
