# Generated by Django 5.2.5 on 2026-09-03 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empaques', '0033_add_dhg_avila_otates'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='invoice_dhg_lopez',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Núm. factura AGRICOLA DH&G LOPEZ'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='order_dhg_lopez',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Núm. orden AGRICOLA DH&G LOPEZ'),
        ),
        migrations.AlterField(
            model_name='shipmentitem',
            name='cliente',
            field=models.CharField(blank=True, choices=[('La Cima Produce', 'La Cima Produce'), ('RC Organics', 'RC Organics'), ('GH Farms', 'GH Farms'), ('Gourmet Baja Farms', 'Gourmet Baja Farms'), ('GBF Farms', 'GBF Farms'), ('AGRICOLA DH & G', 'AGRICOLA DH & G'), ('AGRICOLA DH&G GONZALO', 'AGRICOLA DH&G GONZALO'), ('AGRICOLA DH&G CRUCES', 'AGRICOLA DH&G CRUCES'), ('PRODUCTORA EL GARAL', 'PRODUCTORA EL GARAL'), ('AGRICOLA DH&G AVILA', 'AGRICOLA DH&G AVILA'), ('AGRICOLA DH&G OTATES', 'AGRICOLA DH&G OTATES'), ('AGRICOLA DH&G LOPEZ', 'AGRICOLA DH&G LOPEZ')], max_length=32, null=True),
        ),
    ]
