# Generated by Django 5.2.5 on 2026-01-09 22:50

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'verbose_name': 'Campo',
                'verbose_name_plural': 'Campos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Presentacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etiqueta', models.CharField(max_length=20, unique=True)),
                ('onzas', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0.01)])),
            ],
            options={
                'verbose_name': 'Presentación',
                'verbose_name_plural': 'Presentaciones',
                'ordering': ['onzas'],
            },
        ),
        migrations.CreateModel(
            name='Variedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'verbose_name': 'Variedad',
                'verbose_name_plural': 'Variedades',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Embarque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('destino', models.CharField(choices=[('GOURMET', 'Gourmet'), ('CRAVO', 'Cravo'), ('ABIERTO', 'Abierto'), ('NUEVO', 'Nuevo')], max_length=10)),
                ('numero', models.CharField(blank=True, max_length=30, null=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('campo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='embarques', to='arandano.campo')),
            ],
            options={
                'verbose_name': 'Embarque',
                'verbose_name_plural': 'Embarques',
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.CreateModel(
            name='EmbarqueItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cajas', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('embarque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='arandano.embarque')),
                ('presentacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='arandano.presentacion')),
                ('variedad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='arandano.variedad')),
            ],
            options={
                'verbose_name': 'Ítem de embarque',
                'verbose_name_plural': 'Ítems de embarque',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='CampoVariedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variedades_permitidas', to='arandano.campo')),
                ('variedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campos', to='arandano.variedad')),
            ],
            options={
                'verbose_name': 'Variedad permitida por campo',
                'verbose_name_plural': 'Variedades permitidas por campo',
                'ordering': ['campo__nombre', 'variedad__nombre'],
                'unique_together': {('campo', 'variedad')},
            },
        ),
    ]
