# Generated by Django 5.2.5 on 2026-01-12 16:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arandano', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='embarqueitem',
            name='embarque',
        ),
        migrations.RemoveField(
            model_name='embarqueitem',
            name='presentacion',
        ),
        migrations.RemoveField(
            model_name='embarqueitem',
            name='variedad',
        ),
        migrations.AlterModelOptions(
            name='campo',
            options={'verbose_name': 'Campo', 'verbose_name_plural': 'Campos'},
        ),
        migrations.AlterModelOptions(
            name='campovariedad',
            options={'verbose_name': 'Variedad por campo', 'verbose_name_plural': 'Variedades por campo'},
        ),
        migrations.AlterModelOptions(
            name='variedad',
            options={'verbose_name': 'Variedad', 'verbose_name_plural': 'Variedades'},
        ),
        migrations.AlterField(
            model_name='campovariedad',
            name='campo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variedades', to='arandano.campo'),
        ),
        migrations.CreateModel(
            name='ProduccionDiaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('rezaga_cajas', models.PositiveIntegerField(default=0)),
                ('notas', models.CharField(blank=True, max_length=200)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('campo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='producciones', to='arandano.campo')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Producción diaria',
                'verbose_name_plural': 'Producciones diarias',
                'ordering': ['-fecha', '-id'],
                'unique_together': {('fecha', 'campo')},
            },
        ),
        migrations.CreateModel(
            name='ProduccionRenglon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presentacion', models.CharField(choices=[('P6', 'Presentación 1'), ('P98', 'Presentación 2'), ('P18', 'Presentación 3')], max_length=4)),
                ('cajas', models.PositiveIntegerField(default=0)),
                ('produccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renglones', to='arandano.producciondiaria')),
                ('variedad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='arandano.variedad')),
            ],
            options={
                'verbose_name': 'Renglón de producción',
                'verbose_name_plural': 'Renglones de producción',
            },
        ),
        migrations.DeleteModel(
            name='Embarque',
        ),
        migrations.DeleteModel(
            name='Presentacion',
        ),
        migrations.DeleteModel(
            name='EmbarqueItem',
        ),
    ]
