# Generated by Django 5.2.5 on 2026-01-12 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arandano', '0002_remove_embarqueitem_embarque_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campo',
            options={},
        ),
        migrations.AlterModelOptions(
            name='campovariedad',
            options={},
        ),
        migrations.AlterModelOptions(
            name='variedad',
            options={},
        ),
        migrations.AddField(
            model_name='campo',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='campovariedad',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='variedad',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='campo',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='campovariedad',
            name='campo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arandano.campo'),
        ),
        migrations.AlterField(
            model_name='campovariedad',
            name='variedad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arandano.variedad'),
        ),
        migrations.AlterField(
            model_name='variedad',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='ProduccionDia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('rezaga_cajas', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('notas', models.TextField(blank=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('campo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='arandano.campo')),
            ],
        ),
        migrations.CreateModel(
            name='ProduccionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cajas_6oz', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cajas_9_8oz', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cajas_18oz', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('produccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='arandano.producciondia')),
                ('variedad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='arandano.variedad')),
            ],
            options={
                'unique_together': {('produccion', 'variedad')},
            },
        ),
    ]
