# Generated by Django 5.2.5 on 2026-01-12 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arandano', '0003_alter_campo_options_alter_campovariedad_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produccionrenglon',
            name='produccion',
        ),
        migrations.RemoveField(
            model_name='produccionrenglon',
            name='variedad',
        ),
        migrations.AlterModelOptions(
            name='producciondia',
            options={'ordering': ['-fecha', '-id'], 'verbose_name': 'Producción diaria', 'verbose_name_plural': 'Producciones diarias'},
        ),
        migrations.RenameField(
            model_name='producciondia',
            old_name='rezaga_cajas',
            new_name='rezaga_kg',
        ),
        migrations.RenameField(
            model_name='produccionitem',
            old_name='cajas_18oz',
            new_name='kg',
        ),
        migrations.RemoveField(
            model_name='produccionitem',
            name='cajas_6oz',
        ),
        migrations.RemoveField(
            model_name='produccionitem',
            name='cajas_9_8oz',
        ),
        migrations.AlterField(
            model_name='producciondia',
            name='campo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='producciones', to='arandano.campo'),
        ),
        migrations.AlterUniqueTogether(
            name='producciondia',
            unique_together={('fecha', 'campo')},
        ),
        migrations.DeleteModel(
            name='ProduccionDiaria',
        ),
        migrations.DeleteModel(
            name='ProduccionRenglon',
        ),
    ]
