# Generated by Django 5.2.5 on 2026-01-17 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arandano', '0004_remove_produccionrenglon_produccion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalidaDia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('notas', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('campo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salidas', to='arandano.campo')),
            ],
            options={
                'verbose_name': 'Salida (día)',
                'verbose_name_plural': 'Salidas (días)',
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SalidaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kg', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('salida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='arandano.salidadia')),
                ('variedad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='arandano.variedad')),
            ],
            options={
                'verbose_name': 'Renglón de salida',
                'verbose_name_plural': 'Renglones de salida',
            },
        ),
    ]
