# Generated by Django 5.2.5 on 2026-01-19 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arandano', '0005_salidadia_salidaitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salidadia',
            name='campo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salidas_dia', to='arandano.campo'),
        ),
        migrations.CreateModel(
            name='Salida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('kg', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('notas', models.CharField(blank=True, max_length=200)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('campo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salidas_mov', to='arandano.campo')),
                ('variedad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='salidas_mov', to='arandano.variedad')),
            ],
            options={
                'verbose_name': 'Salida',
                'verbose_name_plural': 'Salidas',
                'ordering': ['-fecha', '-id'],
            },
        ),
    ]
