# Generated by Django 5.2.5 on 2026-01-24 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arandano', '0006_alter_salidadia_campo_salida'),
    ]

    operations = [
        migrations.AddField(
            model_name='produccionitem',
            name='cs_18oz',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='produccionitem',
            name='cs_6oz',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='produccionitem',
            name='cs_9_8oz',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='salidaitem',
            name='cs_18oz',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='salidaitem',
            name='cs_6oz',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='salidaitem',
            name='cs_9_8oz',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
