# Generated by Django 5.2.5 on 2026-01-27 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arandano', '0007_produccionitem_cs_18oz_produccionitem_cs_6oz_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salidaitem',
            name='kg',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=12),
        ),
    ]
