# Generated by Django 5.2.5 on 2026-01-28 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arandano', '0008_alter_salidaitem_kg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produccionitem',
            name='kg',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True),
        ),
    ]
