# Generated by Django 5.2.5 on 2026-02-03 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arandano', '0009_alter_produccionitem_kg'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='salidadia',
            name='destino',
            field=models.CharField(choices=[('EMPAQUE', 'Empaque'), ('OTRO', 'Otro destino')], default='OTRO', max_length=12),
        ),
        migrations.AddField(
            model_name='salidadia',
            name='destino_detalle',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.CreateModel(
            name='InventarioMovimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('CAMPO', 'Campo'), ('EMPAQUE', 'Empaque')], max_length=10)),
                ('fecha', models.DateField()),
                ('concepto', models.CharField(choices=[('ENTRADA_CAMPO', 'Entrada por Producción (Campo)'), ('SALIDA_CAMPO_OTRO', 'Salida Campo (Otro destino)'), ('TRANSFER_CAMPO_A_EMPAQUE', 'Transferencia Campo→Empaque'), ('ENTRADA_EMPAQUE_DESDE_CAMPO', 'Entrada Empaque desde Campo'), ('SALIDA_EMPAQUE_EMBARQUE', 'Salida Empaque por Embarque'), ('AJUSTE', 'Ajuste manual')], max_length=40)),
                ('kg', models.DecimalField(decimal_places=5, default=0, max_digits=12)),
                ('cs_6oz', models.PositiveIntegerField(default=0)),
                ('cs_9_8oz', models.PositiveIntegerField(default=0)),
                ('cs_18oz', models.PositiveIntegerField(default=0)),
                ('notas', models.CharField(blank=True, max_length=200)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('campo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_inv', to='arandano.campo')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('variedad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_inv', to='arandano.variedad')),
            ],
            options={
                'ordering': ['fecha', 'id'],
                'indexes': [models.Index(fields=['scope', 'fecha'], name='arandano_in_scope_7cc2a3_idx'), models.Index(fields=['scope', 'variedad', 'fecha'], name='arandano_in_scope_15a5aa_idx'), models.Index(fields=['scope', 'campo', 'variedad', 'fecha'], name='arandano_in_scope_12aa15_idx')],
            },
        ),
    ]
