# Generated by Django 5.2.5 on 2026-02-03 18:51

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arandano', '0010_salidadia_destino_salidadia_destino_detalle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salidadia',
            name='destino',
            field=models.CharField(choices=[('EMPAQUE', 'Empaque'), ('OTRO', 'Otro destino')], default='OTRO', max_length=10),
        ),
        migrations.CreateModel(
            name='InventoryLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('scope', models.CharField(choices=[('CAMPO', 'Campo'), ('EMPAQUE', 'Empaque')], max_length=10)),
                ('kg', models.DecimalField(decimal_places=5, default=Decimal('0'), max_digits=14)),
                ('cs_6oz', models.IntegerField(default=0)),
                ('cs_9_8oz', models.IntegerField(default=0)),
                ('cs_18oz', models.IntegerField(default=0)),
                ('ref_app', models.CharField(blank=True, max_length=32)),
                ('ref_id', models.CharField(blank=True, max_length=64)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('campo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='arandano.campo')),
                ('variedad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='arandano.variedad')),
            ],
            options={
                'ordering': ['fecha', 'id'],
                'indexes': [models.Index(fields=['scope', 'variedad', 'fecha'], name='arandano_in_scope_ea1a31_idx'), models.Index(fields=['scope', 'variedad', 'campo', 'fecha'], name='arandano_in_scope_d5a36b_idx')],
            },
        ),
    ]
