# Generated by Django 5.2.5 on 2026-02-04 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arandano', '0011_alter_salidadia_destino_inventoryledger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salidadia',
            name='destino',
            field=models.CharField(choices=[('EMPAQUE', 'Empaque'), ('OTRO', 'Otro destino')], default='EMPAQUE', help_text='A dónde va la salida (para mover inventario de Empaque).', max_length=16),
        ),
        migrations.AlterField(
            model_name='salidadia',
            name='destino_detalle',
            field=models.CharField(blank=True, help_text="Si es 'Otro', especifica (cliente/lugar).", max_length=120),
        ),
    ]
