# Generated by Django 5.2.5 on 2026-02-16 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arandano', '0012_alter_salidadia_destino_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salidadia',
            name='destino',
            field=models.CharField(choices=[('EMPAQUE', 'Empaque'), ('OTRO', 'Otro destino')], default='EMPAQUE', max_length=16),
        ),
        migrations.AlterField(
            model_name='salidadia',
            name='destino_detalle',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
