# Generated by Django 5.2.5 on 2026-08-24 15:54

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Credito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(choices=[('LA CIMA', 'La Cima'), ('EMPAQUE N1', 'Empaque N1'), ('RC', 'RC')], max_length=20, verbose_name='Empresa')),
                ('banco', models.CharField(choices=[('BBVA', 'BBVA'), ('BAJIO', 'Bajío'), ('HSBC', 'HSBC'), ('ELEVATE', 'Elevate Export Finance')], max_length=20, verbose_name='Banco')),
                ('tipo_credito', models.CharField(choices=[('CTA_CORRIENTE', 'Cuenta corriente'), ('SIMPLE', 'Crédito simple'), ('CC_GARANTIA_H', 'CC garantía hipotecaria'), ('OTRO', 'Otro (especificar)')], max_length=20, verbose_name='Tipo de crédito')),
                ('tipo_otro', models.CharField(blank=True, help_text="Sólo si el tipo de crédito es 'Otro'.", max_length=120, verbose_name='Especificar tipo')),
                ('moneda', models.CharField(choices=[('MXN', 'Pesos MXN'), ('USD', 'Dólares USD')], default='MXN', max_length=3, verbose_name='Moneda')),
                ('tasa', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='Tasa (%)')),
                ('plazo_meses', models.PositiveIntegerField(blank=True, help_text='Duración del crédito en meses.', null=True, verbose_name='Plazo (meses)')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Monto del crédito')),
                ('fecha_disposicion', models.DateField(verbose_name='Fecha de disposición')),
                ('fecha_vencimiento', models.DateField(help_text='Fecha en que vence el crédito.', verbose_name='Fecha de vencimiento')),
                ('referencia', models.CharField(blank=True, max_length=60, verbose_name='Núm. de crédito / referencia')),
                ('notas', models.TextField(blank=True, verbose_name='Notas')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Crédito',
                'verbose_name_plural': 'Créditos',
                'ordering': ['fecha_vencimiento', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Garantia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True, verbose_name='Nombre del campo / terreno')),
                ('descripcion', models.CharField(blank=True, max_length=255, verbose_name='Descripción')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Garantía',
                'verbose_name_plural': 'Garantías',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Abono',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=datetime.date.today, verbose_name='Fecha del abono')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Monto abonado')),
                ('referencia', models.CharField(blank=True, max_length=60, verbose_name='Referencia')),
                ('nota', models.CharField(blank=True, max_length=255, verbose_name='Nota')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('credito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abonos', to='creditos.credito', verbose_name='Crédito')),
            ],
            options={
                'verbose_name': 'Abono',
                'verbose_name_plural': 'Abonos',
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.AddField(
            model_name='credito',
            name='garantia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='creditos', to='creditos.garantia', verbose_name='Garantía'),
        ),
    ]
