# Generated by Django 5.2.5 on 2026-09-01 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='garantia',
            name='precio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Precio'),
        ),
    ]
