# Generated by Django 5.2.5 on 2026-09-04 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditos', '0002_garantia_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='credito',
            name='cantidad_pagos',
            field=models.PositiveIntegerField(blank=True, help_text='En cuántas exhibiciones se liquida el monto del crédito.', null=True, verbose_name='Cantidad de pagos'),
        ),
        migrations.AddField(
            model_name='credito',
            name='fecha_contratacion',
            field=models.DateField(blank=True, help_text='Fecha en que se contrató el crédito.', null=True, verbose_name='Fecha de crédito'),
        ),
        migrations.AddField(
            model_name='credito',
            name='frecuencia_pagos',
            field=models.CharField(blank=True, choices=[('MENSUAL', 'Mensual'), ('BIMESTRAL', 'Cada 2 meses'), ('TRIMESTRAL', 'Cada 3 meses'), ('SEMESTRAL', 'Cada 6 meses'), ('ANUAL', 'Anual')], help_text='Cada cuánto se paga.', max_length=12, verbose_name='Tiempo de pagos'),
        ),
    ]
