# Generated by Django 5.2.5 on 2026-09-04 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditos', '0003_plan_de_pagos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credito',
            name='frecuencia_pagos',
            field=models.CharField(blank=True, choices=[('MENSUAL', 'Mensual'), ('BIMESTRAL', 'Cada 2 meses'), ('TRIMESTRAL', 'Cada 3 meses'), ('CADA5', 'Cada 5 meses'), ('SEMESTRAL', 'Cada 6 meses'), ('ANUAL', 'Anual')], help_text='Cada cuánto se paga.', max_length=12, verbose_name='Tiempo de pagos'),
        ),
        migrations.AlterField(
            model_name='credito',
            name='tasa',
            field=models.DecimalField(blank=True, decimal_places=12, max_digits=15, null=True, verbose_name='Tasa (%)'),
        ),
    ]
