# Generated by Django 5.2.5 on 2026-09-08 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditos', '0004_tasa_decimales_y_cada5'),
    ]

    operations = [
        migrations.AddField(
            model_name='garantia',
            name='moneda',
            field=models.CharField(choices=[('MXN', 'Pesos MXN'), ('USD', 'Dólares USD')], default='MXN', max_length=3, verbose_name='Moneda del precio'),
        ),
    ]
