# Generated by Django 5.2.5 on 2026-09-18 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditos', '0005_garantia_moneda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credito',
            name='tipo_credito',
            field=models.CharField(choices=[('CTA_CORRIENTE', 'Cuenta corriente'), ('SIMPLE', 'Crédito simple'), ('CC_GARANTIA_H', 'CC garantía hipotecaria'), ('REVOLVENTE', 'Crédito revolvente'), ('OTRO', 'Otro (especificar)')], max_length=20, verbose_name='Tipo de crédito'),
        ),
    ]
